### ISSUE TITLE
Course Feedback from MSFT

### ISSUE THREAD

**Issue by a-a-ron** [githubtraining/hello-github-actions#21]
The below feedback was sent to me from Harshitha, a PM intern under Usha, the product Manager for GitHub Actions for Azure.

#### Course Design Inputs:

- In “Hello GitHub actions” course, the first step is to create a docker file, entrypoint.sh; this is important to understand the environment, but this is not created by a user unless he/she creates a custom action. Since this is an entry level course which requires “Introduction to GitHub” as pre-requisite, introducing to docker file in the first step may not be the first use case of the new user. Rather using a starter workflow, configuring a sample action and running a workflow can be introduced first and creating a custom action can be introduced later. This may be due to the basic workflow course being inaccessible with 404 error.

**Comment by hectorsector** [comment]
I tend to agree that this course isn't the best introductory level content for GitHub Actions, but it does show from consuming to creating an action is a short, all-encompassing course. 

I don't think the right thing to do here is to change the course, but rather to work on an introductory Workflow course and add it to the path (perhaps before this course).

/cc @mattdavis0351 for thoughts

**Comment by brianamarie** [comment]
My understanding from this feedback is that it's a request for more introductory level  content on GitHub Actions. Since late April, we've created many more courses, including the Learning Path, and some of our paid PS offerings. Because of these changes, and the lack of similar feedback on this topic, I am going to close this issue.
